title: Cultural Misrepresentations in AI
description: Research on cultural bias and misrepresentation in Large Language Models
theme: jekyll-theme-minimal
show_downloads: false
google_analytics: # Add your GA tracking ID if needed

