# Site settings
title: Cultural Representation of AI-Generated Stories
description: Research on cultural bias and misrepresentation in Large Language Models
url: "https://cultural-misrepresentations.github.io"

# Build settings
# Using static HTML files - no Jekyll theme needed
